import type { Metadata } from 'next';
import './globals.css';
import { inter, interTight } from '@/app/lib/font';
import Header from './ui/Header/header';
import Footer from './ui/Footer/Footer';

export const metadata: Metadata = {
  title: 'Landus : SkyScout',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${inter.variable} ${interTight.variable}`}>
      <body className={`${inter.className} antialiased`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
