// app/layout.tsx (Server Component — correct)
import type { Metadata } from 'next';
import './globals.css';
import { inter, interTight } from '@/app/lib/font';
import HeaderWrapper from './ui/Header/header'; // NEW component
import { navItems, promotionData, promotionLink, SocialMediaLinks } from './lib/data';
import Header from './ui/Header/header';

export const metadata: Metadata = {
  title: 'Landus : SkyScout',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${inter.variable} ${interTight.variable}`}>
      <body className={`${inter.className} antialiased`}>
        <Header
          promotionData={promotionData}
          promotionLink={promotionLink}
          socialMediaList={SocialMediaLinks}
          navItems={navItems}
        />
        {children}
      </body>
    </html>
  );
}
